# Generated by Django 5.0.3 on 2024-10-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('generic_name', models.CharField(max_length=150)),
                ('manufacturer', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('batch_number', models.CharField(max_length=50)),
                ('form', models.CharField(max_length=100)),
                ('stock_quantity', models.IntegerField()),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
    ]
